### PR TITLE
Dracula Pro Color Scheme

### PR DESCRIPTION
**Pull request by ghost**
A color scheme based on the configuration of pastel-dark using the color palette from Dracula Pro's official theme design repository. I just used the standard color palette with some of the colors for "Buffy" to add an edge to the design. All colors are official. I do not own Dracula Pro or Dracula, I simply purchased the Pro Theme from the official website and loved the layout so I decided to make my Notion Theme match my desktop and IDE themes.

### CODE REVIEW

**Comment by dragonwocky** [comment]
Before I merge this: is this allowed by the license terms of Dracula Pro? As in, is it the themes specifically that are copyrighted or the colour palette?
I can see you've licensed this theme under your own name, but if you've copied from a commercially licensed product that could be problematic.

**Comment by mimi-shahzad** [comment]
> Before I merge this: is this allowed by the license terms of Dracula Pro? As in, is it the themes specifically that are copyrighted or the colour palette?
> I can see you've licensed this theme under your own name, but if you've copied from a commercially licensed product that could be problematic.

@dragonwocky I think you're right about that actually.. I just thought that others would like to use a theme that matches the Dracula Pro set. It is not mine by any means, they give the palette away with the download after you purchase the theme, which I did, but if there's some type of legal issue then I'd rather close the PR, and call it a day. I don't want any trouble.

**Comment by dragonwocky** [comment]
I mean it's not likely anything would actually happen but I'd still rather err on the side of doing the right thing by the creator.

It would be good to port the normal version of the Dracula theme, though: if you'd be interested in doing that that'd be great.

**Comment by mimi-shahzad** [comment]
> I mean it's not likely anything would actually happen but I'd still rather err on the side of doing the right thing by the creator.
> 
> It would be good to port the normal version of the Dracula theme, though: if you'd be interested in doing that that'd be great.

That's a great idea, I appreciate the support~ Thank you for pointing that out, I honestly hadn't thought of the legal aspect at all. I'll try that actually because regular Dracula is still pretty awesome.

**Comment by Dhyfer1** [comment]
@ghost! Hi, I want to leave you a private message. Do you have an email to contact you?

**Pull request closed without merging**
