### PR TITLE
New extensions: side panel and outliner

### PR DESCRIPTION
**Pull request by CloudHill**
side-panel-demo

# outliner

as suggested by #252.
the outliner is a panel extension that displays a table of contents listing the current page's header blocks.
you can navigate to any header by clicking on it on the panel.

# side panel

the side panel extension serves as a container for other mods to display some information on a panel.
the extension will only execute if any panel extension is enabled.

### creating a panel extension

to create a panel extension, add a `panel` key to `mod.js` with either a string or an object value.
it is also recommended to add `panel` to the extension's tags.

- as a string, the value should be a relative path to an html file to be rendered on the panel.
- as an object, the value can have the following properties:

|  key | description | type |
| --- | ---------- | ---- |
| html | relative path to an html file to be rendered on the panel. | string |
| name (optional) | title to be displayed on the panel - falls back to the name defined in the exports object. | string |
| icon (optional) | relative path to an svg to be displayed as the panel's icon - falls back to the first letter of `name`. | string |
| js (optional) | relative path to a js module. the module should return an object with functions that will be executed in various events. | string |
| fullHeight (optional) | by default, the panel will shrink to its content's height when unlocked. set to `true` to prevent this. | boolean |
| reload (optional) | set to true to show a reload button on the panel | boolean |

example:
```js
module.exports = {
  id: '87e077cc-5402-451c-ac70-27cc4ae65546',
  tags: ['extension', 'panel'],
  name: 'outliner',
  desc: 'table of contents.',
  version: '1.0.0',
  author: 'CloudHill',
  panel: {
    html: "panel.html",
    name: "Outline",
    icon: "icon.svg",
    js: "panel.js",
  }
};
```

### panel event functions

your js module should return an object with one or more of these functions:

- `onLoad()` runs after your html is rendered.
- `onSwitch()` runs when the user switches to another panel extension.
- `onUnlock()` runs when the panel is unlocked.
- `onLock()` runs when the panel is locked.
- `onResize()` runs when the user resizes the panel using the resize handle.

### CODE REVIEW

**Comment by admiraldus** [comment]
can you make an animation almost same to the left sidebar?

**Comment by woniuxia** [comment]
looking forward！

**Comment by laichunguang1** [comment]
Thank you! This extionsion is awesome. But I could I scroll in outliner when my table of contents is too long? Because it only show the front part of it.

**Comment by dragonwocky** [comment]
@laichunguang1 see https://github.com/notion-enhancer/repo/issues/30, not being able to scroll is a bug

**Comment by laichunguang1** [comment]
I see, thank you. Hope it will be fixed soon!

**Pull request merged**
